### ISSUE TITLE
Can't install agate-charts from PyPI

### ISSUE THREAD

**Issue by TaurusOlson** [wireservice/agate-charts#26]
The command:

```
pip install agate-charts
```

gives me the following error:

```
Collecting agate-charts
  Could not find a version that satisfies the requirement agate-charts (from versions: )
No matching distribution found for agate-charts
```

However 

```
pip install -r requirements.txt
```

in the repository works correctly.

**Comment by russellgoldenberg** [comment]
I am getting the same problem trying to install from conda. Tried envs with python version 3.5 (thought that might be the issue) and 3.3.

**Comment by scottpham** [comment]
Hi, I am also experiencing this issue. Same error message. Any insight on this?  Here are some relevant details for my system:

OS: Mac OS X 10.11.1
Python version: 2.7.11
Pip version: 8.1.1

**Comment by eads** [comment]
same here!

**Comment by jpmckinney** [comment]
Looks like the release was created on PyPI without uploading the artifact... Anyway, 0.1.1 is released!
